version: "2.1"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    security_opt:
      - no-new-privileges:true
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # Frontend
      - "traefik.http.routers.frontend.entrypoints=web,websecure"
      - "traefik.http.routers.frontend.rule=Host(`portainer.docker.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls=true"
      #- "traefik.http.routers.frontend.tls.certresolver=certificates"
      # Edge
      - "traefik.http.routers.edge.entrypoints=web,websecure"
      - "traefik.http.routers.edge.rule=Host(`edge.docker.localhost`)"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls=true"
      #- "traefik.http.routers.edge.tls.certresolver=certificates"
    networks:
      - proxy
      
networks:
  proxy:
    external: true
    
volumes:
  portainer_data:
